### ISSUE TITLE
Fatal error when switching woo-order statute from completed to on-hold (not very usefull but might happend)

### ISSUE THREAD

**Issue by jbonlinea** [WPCV/wpcv-woo-civi-integration#12]
```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function WPCV_Woo_Civi_Contribution::status_update(), 2 passed in /path/to/wpcv-woo-civi-integration/includes/classes/class-woo-civi-order.php on line 249 and exactly 3 expected in /home/www/wp-content/plugins/wpcv-woo-civi-integration/includes/classes/class-woo-civi-contribution.php:818 
Stack trace: 
#0 /path/to/wpcv-woo-civi-integration/includes/classes/class-woo-civi-order.php(249): WPCV_Woo_Civi_Contribution->status_update(141, 2) 
#1 /path/to/wp-includes/class-wp-hook.php(303): WPCV_Woo_Civi_Order->order_status_changed(141, 'completed', 'processing', Object(WC_Order)) 
#2 /path/to/wp-includes/class-wp-hook.php(327): WP_Hook->apply_f in /home/www/wp-content/plugins/wpcv-woo-civi-integration/includes/classes/class-woo-civi-contribution.php on line 818

There has been a critical error on this website. Please check your site admin email inbox for instructions.
```

**Comment by christianwach** [comment]
Should be solved by #14 - please reopen if not.
