### ISSUE TITLE
Internal server error on woocommerce subscription purchase 

### ISSUE THREAD

**Issue by monishdeb** [WPCV/wpcv-woo-civi-integration#30]
```
[Tue May 03 03:20:52.777930 2022] [php7:error] [pid 3317026] [client 103.24.85.72:51833] 
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WPCV_Woo_Civi_Source::order_updated(), 1 passed in /var/www/example.com/htdocs/wp-includes/class-wp-hook.php on line 307 
and exactly 2 expected in /var/www/example.com/htdocs/wp-content/plugins/wpcv-woo-civi-integration/includes/classes/class-woo-civi-source.php:152
\nStack trace:\n#0 /var/www/example.com/htdocs/wp-includes/class-wp-hook.php(307): WPCV_Woo_Civi_Source->order_updated()
\n#1 /var/www/example.com/htdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
\n#2 /var/www/example.com/htdocs/wp-includes/plugin.php(474): WP_Hook->do_action()
\n#3 /var/www/example.com/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/data-stores/class-wcs-subscription-data-store-cpt.php(189): do_action()
\n#4 /var/www/example.com/htdocs/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(179): WCS_Subscription_Data_Store_CPT->update()
\n#5 /var/www/nutritionco in /var/www/example.com/htdocs/wp-content/plugins/wpcv-woo-civi-integration/includes/classes/class-woo-civi-source.php on line 152,
referer: https://example.com/checkout/
```

On debug, I found that WPCV_Woo_Civi_Source adds action `order_updated`, via `woocommerce_update_order` hook with two arguments, but as per hook definition [here](http://hookr.io/actions/woocommerce_update_order/) it expects one argument `$order_id`.  This trigger fatal error of type ArgumentCountError due to the associated plugin [WooCommerce Subscriptions](https://www.woocommerce.com/products/woocommerce-subscriptions/) .

**Comment by monishdeb** [comment]
@christianwach I have submitted PR https://github.com/WPCV/wpcv-woo-civi-integration/pull/31 for the fix

**Comment by Edzelopez** [comment]
@christianwach if the PR looks good, you might want to update other places where the add_action('woocommerce_update_order') is called.

**Comment by christianwach** [comment]
Hi @monishdeb @Edzelopez This looks to me like it's WooCommerce itself that is at fault for inconsistent implementation of params for the `woocommerce_update_order` action:

https://github.com/woocommerce/woocommerce/search?q=woocommerce_update_order

I notice that it's only when using the WooCommerce REST API that the action is called with the second param missing. Is that what you're doing?

I agree that the callbacks in this plugin should guard against the missing param, but I would recommend opening an issue (and maybe a PR) on Woo itself to resolve this inconsistency.

**Comment by monishdeb** [comment]
@christianwach I have managed to prepare a screencast: 
![before](https://user-images.githubusercontent.com/3735621/166636749-8478f1d0-e87f-443e-beb3-d171415d3e8d.gif)

The internal AJAX url hitting is - https://example.com/?wc-ajax=checkout that processes the checkout information and eventually triggers an internal server error. Yes you are right the error is generating from 'WooCommerce Subscription' plugin and alternatively I found another fix for this plugin: 
```diff
diff --git a/wp-content/plugins/woocommerce-subscriptions/includes/data-stores/class-wcs-subscription-data-store-cpt.php b/wp-content/plugins/woocommerce-subscriptions/includes/data-stores/class-wcs-subscription-data-store-cpt.php
index 48b6109e6..9b85fceb6 100644
--- a/wp-content/plugins/woocommerce-subscriptions/includes/data-stores/class-wcs-subscription-data-store-cpt.php
+++ b/wp-content/plugins/woocommerce-subscriptions/includes/data-stores/class-wcs-subscription-data-store-cpt.php
@@ -186,7 +186,7 @@ class WCS_Subscription_Data_Store_CPT extends WC_Order_Data_Store_CPT implements
                Abstract_WC_Order_Data_Store_CPT::update( $subscription );
 
                // We used to call parent::update() above, which triggered this hook, so we trigger it manually here for backward compatibilty (and to improve compatibility with 3rd party code which may run validation or additional operations on it which should also be applied to a subscription)
-               do_action( 'woocommerce_update_order', $subscription->get_id() );
+               do_action( 'woocommerce_update_order', $subscription->get_id(), $subscription  );
 
                do_action( 'woocommerce_update_subscription', $subscription->get_id() );
        }
 ```

**Comment by christianwach** [comment]
@monishdeb Thanks for this. Seems like there could be a lot of inconsistencies out in the wild.

**Comment by christianwach** [comment]
@monishdeb I assume 00cfe0c154c6990466c7a960bca73174eab2b6b0 fixed this. Please re-open if not.
